import type { RoleCode } from '@core/config/experience/experience.models';
import type { DashboardRoleConfig } from './dashboard.models';

const configs: Readonly<Record<RoleCode, DashboardRoleConfig>> = {
  general_manager: {
    role: 'general_manager',
    experience: 'desktop',
    eyebrow: 'Vista global',
    title: 'Centro de control global',
    subtitle: 'Supervisa la operación disponible en todas las sucursales.',
    showKpis: true,
    showQuickActions: false,
    showReports: true,
    showRecentActivity: true,
    showPendingItems: true,
    showAlerts: true,
    quickActionIds: [],
    sectionOrder: ['applications', 'delinquency', 'cutoffs', 'points'],
  },
  branch_manager: {
    role: 'branch_manager',
    experience: 'desktop',
    eyebrow: 'Tu sucursal',
    title: 'Centro de control de sucursal',
    subtitle: 'Consulta la operación y los pendientes dentro de tu alcance vigente.',
    showKpis: true,
    showQuickActions: false,
    showReports: true,
    showRecentActivity: true,
    showPendingItems: true,
    showAlerts: true,
    quickActionIds: [],
    sectionOrder: ['applications', 'delinquency', 'cutoffs', 'points'],
  },
  admin: {
    role: 'admin',
    experience: 'desktop',
    eyebrow: 'Consulta global · Solo lectura',
    title: 'Centro de consulta y auditoría',
    subtitle: 'Visibilidad global del estado y la actividad de MisVales, sin acciones operativas.',
    showKpis: true,
    showQuickActions: false,
    showReports: true,
    showRecentActivity: true,
    showPendingItems: true,
    showAlerts: true,
    quickActionIds: [],
    sectionOrder: ['applications', 'cutoffs', 'delinquency', 'points'],
  },
  cashier: {
    role: 'cashier',
    experience: 'desktop',
    eyebrow: 'Operación diaria',
    title: 'Operación de caja',
    subtitle: 'Atiende vales, archivo bancario y conciliaciones autorizadas para tu sucursal.',
    showKpis: true,
    showQuickActions: true,
    showReports: false,
    showRecentActivity: true,
    showPendingItems: true,
    showAlerts: true,
    quickActionIds: ['cashier', 'payments', 'reconciliation', 'clarifications'],
    sectionOrder: ['cashier-activity', 'cashier-pending', 'cashier-movements'],
  },
  coordinator: {
    role: 'coordinator',
    experience: 'tablet',
    eyebrow: 'Coordinación',
    title: 'Centro de atención',
    subtitle: 'Prioriza pendientes, distribuidoras y verificaciones dentro de tu alcance.',
    showKpis: true,
    showQuickActions: true,
    showReports: false,
    showRecentActivity: true,
    showPendingItems: true,
    showAlerts: false,
    quickActionIds: ['distributors', 'credit-increases', 'reconciliation'],
    sectionOrder: ['assigned-applications', 'application-summary'],
  },
  verifier: {
    role: 'verifier',
    experience: 'tablet',
    eyebrow: 'Verificación',
    title: 'Mi jornada de verificación',
    subtitle: 'Ubica tu siguiente visita, continúa evidencias y entrega resultados.',
    showKpis: true,
    showQuickActions: true,
    showReports: false,
    showRecentActivity: true,
    showPendingItems: true,
    showAlerts: false,
    quickActionIds: ['verifier-visits'],
    sectionOrder: ['assigned-visits', 'visit-summary'],
  },
  distributor: {
    role: 'distributor',
    experience: 'mobile',
    eyebrow: 'Tu operación',
    title: 'Hola',
    subtitle: 'Gestiona tu crédito, vales y relaciones desde un solo lugar.',
    showKpis: true,
    showQuickActions: true,
    showReports: true,
    showRecentActivity: true,
    showPendingItems: true,
    showAlerts: true,
    quickActionIds: ['vouchers', 'relations', 'payments', 'credit-increases'],
    sectionOrder: [
      'credit-summary',
      'financial-attention',
      'recent-vouchers',
      'points-summary',
      'pending-relations',
      'distributor-activity',
    ],
  },
};

const fallback: DashboardRoleConfig = {
  role: 'admin',
  experience: 'desktop',
  eyebrow: 'Inicio',
  title: 'MisVales',
  subtitle: 'Consulta los módulos disponibles para tu sesión.',
  showKpis: true,
  showQuickActions: true,
  showReports: false,
  showRecentActivity: false,
  showPendingItems: false,
  showAlerts: false,
  quickActionIds: [],
  sectionOrder: [],
};

const priority: readonly RoleCode[] = [
  'general_manager',
  'branch_manager',
  'admin',
  'cashier',
  'coordinator',
  'verifier',
  'distributor',
];

export function dashboardConfigForRoles(roles: readonly string[]): DashboardRoleConfig {
  const role = priority.find((candidate) => roles.includes(candidate));
  return role ? configs[role] : fallback;
}
