import {
  ApplicationConfig,
  ErrorHandler,
  Injectable,
  importProvidersFrom,
  isDevMode,
  provideZonelessChangeDetection,
} from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideHttpClient, withFetch, withInterceptors, withXsrfConfiguration } from '@angular/common/http';
import { routes } from './app.routes';
import { authInterceptor } from '@core/interceptors/auth.interceptor';
import { errorHandlingInterceptor } from '@core/interceptors/error-handling.interceptor';
import { API_CONFIG, defaultApiConfig } from '@core/api/api.config';
import {
  LucideAngularModule,
  Activity,
  AlertTriangle,
  ArrowLeftRight,
  ArrowRightLeft,
  Banknote,
  Bell,
  BellRing,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Calculator,
  CalendarClock,
  CalendarRange,
  ChartNoAxesCombined,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleArrowUp,
  CircleCheck,
  CirclePlus,
  CircleUserRound,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CreditCard,
  Eye,
  EyeOff,
  File,
  FileCheck,
  FileDown,
  FilePenLine,
  FileStack,
  FileTerminal,
  FileText,
  FolderArchive,
  FolderKanban,
  Gift,
  GitMerge,
  GitPullRequest,
  Globe,
  Grid3x3,
  Hash,
  History,
  Inbox,
  Info,
  Key,
  KeyRound,
  Landmark,
  Layers,
  LayoutDashboard,
  Link,
  Loader2,
  Lock,
  LogOut,
  MailPlus,
  Menu,
  MapPin,
  MessageSquare,
  MessageSquareWarning,
  Monitor,
  MonitorSmartphone,
  Move,
  Network,
  OctagonAlert,
  Package,
  PackageCheck,
  PanelLeftClose,
  PanelLeftOpen,
  Percent,
  Plus,
  ReceiptText,
  RefreshCw,
  Save,
  ScanSearch,
  ScrollText,
  Search,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Split,
  Store,
  Tags,
  Target,
  Terminal,
  Ticket,
  TicketCheck,
  TrendingUp,
  Undo2,
  User,
  UserCheck,
  UserCog,
  UserRound,
  UserRoundX,
  Users,
  UsersRound,
  Wallet,
  Workflow,
  X,
} from 'lucide-angular';

@Injectable()
export class GlobalErrorHandler implements ErrorHandler {
  handleError(error: unknown): void {
    if (isDevMode()) {
      console.error('GLOBAL ERROR:', error);
      return;
    }

    console.error('Ocurrió un error inesperado en la aplicación.');
  }
}

export const appConfig: ApplicationConfig = {
  providers: [
    provideZonelessChangeDetection(),
    provideRouter(routes, withComponentInputBinding()),
    provideHttpClient(
      withFetch(),
      withXsrfConfiguration({
        cookieName: 'XSRF-TOKEN',
        headerName: 'X-XSRF-TOKEN',
      }),
      withInterceptors([authInterceptor, errorHandlingInterceptor]),
    ),
    importProvidersFrom(
      LucideAngularModule.pick({
        Activity, AlertTriangle, ArrowLeftRight, ArrowRightLeft, Banknote, Bell, BellRing,
        BookOpen, Briefcase, Building, Building2, Calculator, CalendarClock,
        CalendarRange, ChartNoAxesCombined, CheckCircle, CheckCircle2,
        CheckSquare, ChevronDown, ChevronLeft, ChevronRight, Circle,
        CircleArrowUp, CircleCheck, CirclePlus, CircleUserRound, ClipboardCheck,
        ClipboardList, Clock, CreditCard, Eye, EyeOff, File, FileCheck, FileDown,
        FilePenLine, FileStack, FileTerminal, FileText, FolderArchive,
        FolderKanban, Gift, GitMerge, GitPullRequest, Globe, Grid3x3, Hash,
        History, Inbox, Info, Key, KeyRound, Landmark, Layers, LayoutDashboard,
        Link, Loader2, Lock, LogOut, MailPlus, Menu, MapPin, MessageSquare,
        MessageSquareWarning, Monitor, MonitorSmartphone, Move, Network,
        OctagonAlert, Package, PackageCheck, PanelLeftClose, PanelLeftOpen,
        Percent, Plus, ReceiptText, RefreshCw, Save, ScanSearch, ScrollText,
        Search, Settings, Shield, ShieldAlert, ShieldCheck, SlidersHorizontal,
        Smartphone, Split, Store, Tags, Target, Terminal, Ticket,
        TicketCheck, TrendingUp, Undo2, User, UserCheck, UserCog, UserRound,
        UserRoundX, Users, UsersRound, Wallet, Workflow, X,
      }),
    ),
    { provide: API_CONFIG, useValue: defaultApiConfig },
    { provide: ErrorHandler, useClass: GlobalErrorHandler },
  ],
};
