import {
  ApplicationConfig,
  ErrorHandler,
  importProvidersFrom,
  inject,
  isDevMode,
  provideAppInitializer,
  provideZonelessChangeDetection,
} from '@angular/core';
import { provideRouter, withComponentInputBinding, withInMemoryScrolling } from '@angular/router';
import {
  provideHttpClient,
  withFetch,
  withInterceptors,
  withXsrfConfiguration,
} from '@angular/common/http';
import { routes } from './app.routes';
import { authInterceptor } from '@core/interceptors/auth.interceptor';
import { errorHandlingInterceptor } from '@core/interceptors/error-handling.interceptor';
import { requestActivityInterceptor } from '@core/interceptors/request-activity.interceptor';
import { API_CONFIG, defaultApiConfig } from '@core/api/api.config';
import { GlobalErrorHandler } from '@core/error-handling/global-error-handler';
import { AuthConfigurationService } from '@core/auth/data-access/auth-configuration.service';
import { AccessContextRefreshService } from '@core/auth/services/access-context-refresh.service';
import {
  LucideAngularModule,
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowLeftRight,
  ArrowRightLeft,
  BadgeDollarSign,
  Banknote,
  Bell,
  BellRing,
  BookOpen,
  Briefcase,
  BriefcaseBusiness,
  Building,
  Building2,
  Calculator,
  CalendarDays,
  CalendarCheck,
  CalendarClock,
  CalendarRange,
  ChartNoAxesCombined,
  CheckCircle,
  CheckCircle2,
  CheckCheck,
  Check,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleArrowUp,
  CircleCheck,
  CircleDollarSign,
  CirclePlay,
  CirclePlus,
  CircleUserRound,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Clock3,
  Coins,
  CreditCard,
  Download,
  Eye,
  EyeOff,
  File,
  FileCheck,
  FileDown,
  FilePenLine,
  FileStack,
  FileText,
  FolderArchive,
  FolderKanban,
  Gift,
  GitMerge,
  Globe,
  HandCoins,
  History,
  Hourglass,
  Inbox,
  Info,
  Key,
  KeyRound,
  Landmark,
  Layers,
  LayoutDashboard,
  Link,
  ListFilter,
  ListChecks,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  MailPlus,
  Menu,
  MapPin,
  MessageCircleQuestion,
  MessageSquare,
  Monitor,
  MonitorSmartphone,
  Move,
  OctagonAlert,
  Package,
  PackageCheck,
  PanelLeftClose,
  PanelLeftOpen,
  Percent,
  Play,
  Phone,
  Plus,
  ReceiptText,
  RefreshCw,
  Route,
  Save,
  ScanSearch,
  Scissors,
  ScrollText,
  Search,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Split,
  Store,
  Tags,
  Target,
  Terminal,
  Ticket,
  TicketCheck,
  TriangleAlert,
  TrendingUp,
  Undo2,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserPlus,
  UserRound,
  UserRoundX,
  UserX,
  Users,
  UsersRound,
  Wallet,
  X,
  XCircle,
} from 'lucide-angular';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZonelessChangeDetection(),
    provideAppInitializer(() => {
      if (typeof window !== 'undefined' && 'serviceWorker' in navigator) {
        navigator.serviceWorker.getRegistrations().then((registrations) => {
          for (const registration of registrations) {
            void registration.unregister();
          }
        });
        if ('caches' in window) {
          caches.keys().then((keys) => {
            for (const key of keys) {
              if (key.includes('ngsw')) {
                void caches.delete(key);
              }
            }
          });
        }
      }
    }),
    provideAppInitializer(() => inject(AuthConfigurationService).load()),
    provideAppInitializer(() => inject(AccessContextRefreshService).start()),
    provideRouter(
      routes,
      withComponentInputBinding(),
      withInMemoryScrolling({
        anchorScrolling: 'enabled',
        scrollPositionRestoration: 'enabled',
      }),
    ),
    provideHttpClient(
      withFetch(),
      withXsrfConfiguration({
        cookieName: 'XSRF-TOKEN',
        headerName: 'X-XSRF-TOKEN',
      }),
      withInterceptors([requestActivityInterceptor, authInterceptor, errorHandlingInterceptor]),
    ),
    importProvidersFrom(
      LucideAngularModule.pick({
        Activity,
        AlertTriangle,
        ArrowLeft,
        ArrowRight,
        ArrowLeftRight,
        ArrowRightLeft,
        BadgeDollarSign,
        Banknote,
        Bell,
        BellRing,
        BookOpen,
        Briefcase,
        BriefcaseBusiness,
        Building,
        Building2,
        Calculator,
        CalendarDays,
        CalendarCheck,
        CalendarClock,
        CalendarRange,
        ChartNoAxesCombined,
        CheckCircle,
        CheckCircle2,
        CheckCheck,
        Check,
        CheckSquare,
        ChevronDown,
        ChevronLeft,
        ChevronRight,
        Circle,
        CircleArrowUp,
        CircleCheck,
        CircleDollarSign,
        CirclePlay,
        CirclePlus,
        CircleUserRound,
        ClipboardCheck,
        ClipboardList,
        Clock,
        Clock3,
        Coins,
        CreditCard,
        Download,
        Eye,
        EyeOff,
        File,
        FileCheck,
        FileDown,
        FilePenLine,
        FileStack,
        FileText,
        FolderArchive,
        FolderKanban,
        Gift,
        GitMerge,
        Globe,
        HandCoins,
        History,
        Hourglass,
        Inbox,
        Info,
        Key,
        KeyRound,
        Landmark,
        Layers,
        LayoutDashboard,
        Link,
        ListFilter,
        ListChecks,
        Loader2,
        Lock,
        LogIn,
        LogOut,
        MailPlus,
        Menu,
        MapPin,
        MessageCircleQuestion,
        MessageSquare,
        Monitor,
        MonitorSmartphone,
        Move,
        OctagonAlert,
        Package,
        PackageCheck,
        PanelLeftClose,
        PanelLeftOpen,
        Percent,
        Play,
        Phone,
        Plus,
        ReceiptText,
        RefreshCw,
        Route,
        Save,
        ScanSearch,
        Scissors,
        ScrollText,
        Search,
        Settings,
        Shield,
        ShieldAlert,
        ShieldCheck,
        SlidersHorizontal,
        Smartphone,
        Split,
        Store,
        Tags,
        Target,
        Terminal,
        Ticket,
        TicketCheck,
        TriangleAlert,
        TrendingUp,
        Undo2,
        Unlock,
        Upload,
        User,
        UserCheck,
        UserCog,
        UserPlus,
        UserRound,
        UserRoundX,
        UserX,
        Users,
        UsersRound,
        Wallet,
        X,
        XCircle,
      }),
    ),
    { provide: API_CONFIG, useValue: defaultApiConfig },
    { provide: ErrorHandler, useClass: GlobalErrorHandler },
  ],
};
